modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="darkium"
version="1.0.0"
displayName="Darkium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="dag0 ,  skulljocker"

[[dependencies.darkium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




